export const CAR_MAKES = [
    { label: "A", items: ["Acura", "Alfa Romeo", "Aston Martin", "Audi"] },
    { label: "B", items: ["Bentley", "BMW", "Bugatti", "Buick"] },
    { label: "C", items: ["Cadillac", "Chevrolet", "Chrysler"] },
    { label: "D", items: ["Dodge"] },
    { label: "F", items: ["Ferrari", "FIAT", "Ford"] },
    { label: "G", items: ["Genesis", "GMC"] },
    { label: "H", items: ["Honda", "Hummer", "Hyundai"] },
    { label: "I", items: ["Infiniti", "Isuzu"] },
    { label: "J", items: ["Jaguar", "Jeep"] },
    { label: "K", items: ["Karma", "Kia"] },
    {
        label: "L",
        items: [
            "Lamborghini",
            "Land Rover",
            "Lexus",
            "Lincoln",
            "Lotus",
            "Lucid",
        ],
    },
    {
        label: "M",
        items: [
            "Maserati",
            "Mazda",
            "McLaren",
            "Mercedes-Benz",
            "Mercury",
            "MINI",
            "Mitsubishi",
        ],
    },
    { label: "N", items: ["Nissan"] },
    { label: "O", items: ["Oldsmobile"] },
    {
        label: "P",
        items: ["Packard", "Pagani", "Polestar", "Pontiac", "Porsche"],
    },
    { label: "R", items: ["Ram", "Rivian", "Rolls-Royce"] },
    {
        label: "S",
        items: ["Saab", "Saturn", "Scion", "smart", "SRT", "Subaru", "Suzuki"],
    },
    { label: "T", items: ["Tesla", "Toyota"] },
    { label: "V", items: ["Volkswagen", "Volvo"] },
    {
        label: "Other",
        items: [
            "AC Cars",
            "Alpine",
            "AMC",
            "Avanti",
            "Bristol",
            "Caterham",
            "Daewoo",
            "Daihatsu",
            "Datsun",
            "DeLorean",
            "Fisker",
            "Geo",
            "Hennessey",
            "Hudson",
            "Jensen",
            "Koenigsegg",
            "Lancia",
            "Maybach",
            "MG",
            "Morgan",
            "Noble",
            "Opel",
            "Panoz",
            "Peugeot",
            "Pininfarina",
            "Plymouth",
            "Qvale",
            "Renault",
            "Saleen",
            "Shelby",
            "Spyker",
            "Studebaker",
            "Sunbeam",
            "Triumph",
        ],
    },
];
